---
ansible_user: arye
kind_repo: "https://kind.sigs.k8s.io/dl/{{ kind_version }}/kind-linux-amd64"

required_packages:
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - kubectl

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
